#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# panel
polybar -c /home/ingrid/.config/polybar/config bspwm-bar &

# enabling numpad numbers
numlockx on

# wallpaper and colors
wal -R &

# Set some bsp specific stuff
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 10
bspc config border_width 2

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
