# Shell variables
# Generated by 'wal'
wallpaper='/home/ingrid/Downloads/QRscDhg.png'

# Special
background='#1C2023'
foreground='#dde0e7'
cursor='#dde0e7'

# Colors
color0='#1C2023'
color1='#75A8CC'
color2='#9399AE'
color3='#D3B39E'
color4='#F1D4B5'
color5='#A5B2CD'
color6='#BAC5DD'
color7='#dde0e7'
color8='#9a9ca1'
color9='#75A8CC'
color10='#9399AE'
color11='#D3B39E'
color12='#F1D4B5'
color13='#A5B2CD'
color14='#BAC5DD'
color15='#dde0e7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
