--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ingrid/Downloads/QRscDhg.png"

-- Special
background="#1C2023"
foreground="#dde0e7"
cursor="#dde0e7"

-- Colors
color0="#1C2023"
color1="#75A8CC"
color2="#9399AE"
color3="#D3B39E"
color4="#F1D4B5"
color5="#A5B2CD"
color6="#BAC5DD"
color7="#dde0e7"
color8="#9a9ca1"
color9="#75A8CC"
color10="#9399AE"
color11="#D3B39E"
color12="#F1D4B5"
color13="#A5B2CD"
color14="#BAC5DD"
color15="#dde0e7"
