#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# set panel
killall xfce4-panel && xfce4-panel &

# wallpaper and colors
. "${HOME}/.cache/wal/colors.sh"
(wal -r &)

# set bsp monitor assignment 
bspc monitor eDP1 -d 一 二 三 四 五 六 七 八 九 十

# set dual monitor layout
#if [ "$(bspc query -M | wc -l)" = 2 ]; then
#    $HOME/.screenlayout/dual_setup.sh
#    bspc monitor eDP1 -d 一 二 三 四 五
#    bspc monitor HDMI2 -d 六 七 八 九 十
#else
#    bspc monitor eDP1 -d 一 二 三 四 五 六 七 八 九 十
#fi

# set some bsp specific stuff
bspc config window_gap 8
bspc config border_width 2

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
