#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# enable mictray and blueman-applet
mictray &
blueman-applet &

# panel
$HOME/.config/polybar/polybar_start.sh

# wallpaper and colors
. "${HOME}/.cache/wal/colors.sh"
(wal -r &)

# Set some bsp specific stuff
bspc monitor -d 1 2 3 4 5

bspc config window_gap 12
bspc config border_width 2

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
